# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  config.vm.network :forwarded_port, guest: 5656, host: 5656
  config.vm.provision :shell, :path => "blank-box-init"
end
